server:
 port: 8080

feign:
 client:
  config:
   default:
    connectTimeout: 5000
    readTimeout: 5000
    loggerLevel: BASIC

walletclient:
 baseUrl: "https://api.mercadopago.com"
 token: "Bearer TEST-2933677929195917-012709-99566d73916680b8b167cf1201699e3c-443418201"
